// 
// FLXmlParserErrorCode.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 7/6/13 9:48 AM with PackMule (3.0.0.32)
// 
// Project: FishLamp
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLTypeSpecificEnumSet.h"

typedef enum {
    FLXmlParserErrorCodeInternal = 1,
    FLXmlParserErrorCodeOutOfMemory = 2,
    FLXmlParserErrorCodeDocumentStart = 3,
    FLXmlParserErrorCodeEmptyDocument = 4,
    FLXmlParserErrorCodePrematureDocumentEnd = 5,
    FLXmlParserErrorCodeInvalidHexCharacterRef = 6,
    FLXmlParserErrorCodeInvalidDecimalCharacterRef = 7,
    FLXmlParserErrorCodeInvalidCharacterRef = 8,
    FLXmlParserErrorCodeInvalidCharacter = 9,
    FLXmlParserErrorCodeCharacterRefAtEOF = 10,
    FLXmlParserErrorCodeCharacterRefInProlog = 11,
    FLXmlParserErrorCodeCharacterRefInEpilog = 12,
    FLXmlParserErrorCodeCharacterRefInDTD = 13,
    FLXmlParserErrorCodeEntityRefAtEOF = 14,
    FLXmlParserErrorCodeEntityRefInProlog = 15,
    FLXmlParserErrorCodeEntityRefInEpilog = 16,
    FLXmlParserErrorCodeEntityRefInDTD = 17,
    FLXmlParserErrorCodeParsedEntityRefAtEOF = 18,
    FLXmlParserErrorCodeParsedEntityRefInProlog = 19,
    FLXmlParserErrorCodeParsedEntityRefInEpilog = 20,
    FLXmlParserErrorCodeParsedEntityRefInInternalSubset = 21,
    FLXmlParserErrorCodeEntityReferenceWithoutName = 22,
    FLXmlParserErrorCodeEntityReferenceMissingSemi = 23,
    FLXmlParserErrorCodeParsedEntityRefNoName = 24,
    FLXmlParserErrorCodeParsedEntityRefMissingSemi = 25,
    FLXmlParserErrorCodeUndeclaredEntity = 26,
    FLXmlParserErrorCodeUnparsedEntity = 28,
    FLXmlParserErrorCodeEntityIsExternal = 29,
    FLXmlParserErrorCodeEntityIsParameter = 30,
    FLXmlParserErrorCodeUnknownEncoding = 31,
    FLXmlParserErrorCodeEncodingNotSupported = 32,
    FLXmlParserErrorCodeStringNotStarted = 33,
    FLXmlParserErrorCodeStringNotClosed = 34,
    FLXmlParserErrorCodeNamespaceDeclaration = 35,
    FLXmlParserErrorCodeEntityNotStarted = 36,
    FLXmlParserErrorCodeEntityNotFinished = 37,
    FLXmlParserErrorCodeLessThanSymbolInAttribute = 38,
    FLXmlParserErrorCodeAttributeNotStarted = 39,
    FLXmlParserErrorCodeAttributeNotFinished = 40,
    FLXmlParserErrorCodeAttributeHasNoValue = 41,
    FLXmlParserErrorCodeAttributeRedefined = 42,
    FLXmlParserErrorCodeLiteralNotStarted = 43,
    FLXmlParserErrorCodeLiteralNotFinished = 44,
    FLXmlParserErrorCodeCommentNotFinished = 45,
    FLXmlParserErrorCodeProcessingInstructionNotStarted = 46,
    FLXmlParserErrorCodeProcessingInstructionNotFinished = 47,
    FLXmlParserErrorCodeNotationNotStarted = 48,
    FLXmlParserErrorCodeNotationNotFinished = 49,
    FLXmlParserErrorCodeAttributeListNotStarted = 50,
    FLXmlParserErrorCodeAttributeListNotFinished = 51,
    FLXmlParserErrorCodeMixedContentDeclNotStarted = 52,
    FLXmlParserErrorCodeMixedContentDeclNotFinished = 53,
    FLXmlParserErrorCodeElementContentDeclNotStarted = 54,
    FLXmlParserErrorCodeElementContentDeclNotFinished = 55,
    FLXmlParserErrorCodeXMLDeclNotStarted = 56,
    FLXmlParserErrorCodeXMLDeclNotFinished = 57,
    FLXmlParserErrorCodeConditionalSectionNotStarted = 58,
    FLXmlParserErrorCodeConditionalSectionNotFinished = 59,
    FLXmlParserErrorCodeExternalSubsetNotFinished = 60,
    FLXmlParserErrorCodeDOCTYPEDeclNotFinished = 61,
    FLXmlParserErrorCodeMisplacedCDATAEndString = 62,
    FLXmlParserErrorCodeCDATANotFinished = 63,
    FLXmlParserErrorCodeMisplacedXMLDeclaration = 64,
    FLXmlParserErrorCodeSpaceRequired = 65,
    FLXmlParserErrorCodeSeparatorRequired = 66,
    FLXmlParserErrorCodeNMTOKENRequired = 67,
    FLXmlParserErrorCodeNAMERequired = 68,
    FLXmlParserErrorCodePCDATARequired = 69,
    FLXmlParserErrorCodeURIRequired = 70,
    FLXmlParserErrorCodePublicIdentifierRequired = 71,
    FLXmlParserErrorCodeLTRequired = 72,
    FLXmlParserErrorCodeGTRequired = 73,
    FLXmlParserErrorCodeLTSlashRequired = 74,
    FLXmlParserErrorCodeEqualExpected = 75,
    FLXmlParserErrorCodeTagNameMismatch = 76,
    FLXmlParserErrorCodeUnfinishedTag = 77,
    FLXmlParserErrorCodeStandaloneValue = 78,
    FLXmlParserErrorCodeInvalidEncodingName = 79,
    FLXmlParserErrorCodeCommentContainsDoubleHyphen = 80,
    FLXmlParserErrorCodeInvalidEncoding = 81,
    FLXmlParserErrorCodeExternalStandaloneEntity = 82,
    FLXmlParserErrorCodeInvalidConditionalSection = 83,
    FLXmlParserErrorCodeEntityValueRequired = 84,
    FLXmlParserErrorCodeNotWellBalanced = 85,
    FLXmlParserErrorCodeExtraContent = 86,
    FLXmlParserErrorCodeInvalidCharacterInEntity = 87,
    FLXmlParserErrorCodeParsedEntityRefInInternal = 88,
    FLXmlParserErrorCodeEntityRefLoop = 89,
    FLXmlParserErrorCodeEntityBoundary = 90,
    FLXmlParserErrorCodeInvalidURI = 91,
    FLXmlParserErrorCodeURIFragment = 92,
    FLXmlParserErrorCodeNoDTD = 94,
    FLXmlParserErrorCodeDelegateAbortedParse = 512,
    FLXmlParserErrorCodeUnknownElement = 1024,
    FLXmlParserErrorCodeObjectNotFound = 1025,
} FLXmlParserErrorCode;

#define kFLXmlParserErrorCodeURIRequired @"URIRequired"
#define kFLXmlParserErrorCodeSeparatorRequired @"SeparatorRequired"
#define kFLXmlParserErrorCodeEntityRefInEpilog @"EntityRefInEpilog"
#define kFLXmlParserErrorCodeInvalidCharacterInEntity @"InvalidCharacterInEntity"
#define kFLXmlParserErrorCodeCharacterRefInEpilog @"CharacterRefInEpilog"
#define kFLXmlParserErrorCodeNAMERequired @"NAMERequired"
#define kFLXmlParserErrorCodeSpaceRequired @"SpaceRequired"
#define kFLXmlParserErrorCodeInvalidDecimalCharacterRef @"InvalidDecimalCharacterRef"
#define kFLXmlParserErrorCodeInvalidEncodingName @"InvalidEncodingName"
#define kFLXmlParserErrorCodePublicIdentifierRequired @"PublicIdentifierRequired"
#define kFLXmlParserErrorCodeProcessingInstructionNotFinished @"ProcessingInstructionNotFinished"
#define kFLXmlParserErrorCodeEntityNotFinished @"EntityNotFinished"
#define kFLXmlParserErrorCodeDocumentStart @"DocumentStart"
#define kFLXmlParserErrorCodeMixedContentDeclNotFinished @"MixedContentDeclNotFinished"
#define kFLXmlParserErrorCodeInvalidCharacter @"InvalidCharacter"
#define kFLXmlParserErrorCodeCharacterRefAtEOF @"CharacterRefAtEOF"
#define kFLXmlParserErrorCodeEntityRefLoop @"EntityRefLoop"
#define kFLXmlParserErrorCodeEntityIsExternal @"EntityIsExternal"
#define kFLXmlParserErrorCodeDOCTYPEDeclNotFinished @"DOCTYPEDeclNotFinished"
#define kFLXmlParserErrorCodeParsedEntityRefInEpilog @"ParsedEntityRefInEpilog"
#define kFLXmlParserErrorCodeAttributeListNotStarted @"AttributeListNotStarted"
#define kFLXmlParserErrorCodeProcessingInstructionNotStarted @"ProcessingInstructionNotStarted"
#define kFLXmlParserErrorCodeAttributeListNotFinished @"AttributeListNotFinished"
#define kFLXmlParserErrorCodeConditionalSectionNotFinished @"ConditionalSectionNotFinished"
#define kFLXmlParserErrorCodeEntityRefInDTD @"EntityRefInDTD"
#define kFLXmlParserErrorCodeParsedEntityRefInInternal @"ParsedEntityRefInInternal"
#define kFLXmlParserErrorCodeInvalidURI @"InvalidURI"
#define kFLXmlParserErrorCodePCDATARequired @"PCDATARequired"
#define kFLXmlParserErrorCodeURIFragment @"URIFragment"
#define kFLXmlParserErrorCodeCDATANotFinished @"CDATANotFinished"
#define kFLXmlParserErrorCodeElementContentDeclNotStarted @"ElementContentDeclNotStarted"
#define kFLXmlParserErrorCodeAttributeHasNoValue @"AttributeHasNoValue"
#define kFLXmlParserErrorCodeParsedEntityRefNoName @"ParsedEntityRefNoName"
#define kFLXmlParserErrorCodeNamespaceDeclaration @"NamespaceDeclaration"
#define kFLXmlParserErrorCodeConditionalSectionNotStarted @"ConditionalSectionNotStarted"
#define kFLXmlParserErrorCodeLTSlashRequired @"LTSlashRequired"
#define kFLXmlParserErrorCodeExternalStandaloneEntity @"ExternalStandaloneEntity"
#define kFLXmlParserErrorCodeUnfinishedTag @"UnfinishedTag"
#define kFLXmlParserErrorCodeParsedEntityRefAtEOF @"ParsedEntityRefAtEOF"
#define kFLXmlParserErrorCodeCommentContainsDoubleHyphen @"CommentContainsDoubleHyphen"
#define kFLXmlParserErrorCodeEntityReferenceWithoutName @"EntityReferenceWithoutName"
#define kFLXmlParserErrorCodeEntityRefAtEOF @"EntityRefAtEOF"
#define kFLXmlParserErrorCodeAttributeRedefined @"AttributeRedefined"
#define kFLXmlParserErrorCodeMixedContentDeclNotStarted @"MixedContentDeclNotStarted"
#define kFLXmlParserErrorCodeParsedEntityRefInInternalSubset @"ParsedEntityRefInInternalSubset"
#define kFLXmlParserErrorCodeEntityIsParameter @"EntityIsParameter"
#define kFLXmlParserErrorCodeLTRequired @"LTRequired"
#define kFLXmlParserErrorCodeXMLDeclNotStarted @"XMLDeclNotStarted"
#define kFLXmlParserErrorCodeUnknownEncoding @"UnknownEncoding"
#define kFLXmlParserErrorCodePrematureDocumentEnd @"PrematureDocumentEnd"
#define kFLXmlParserErrorCodeInvalidHexCharacterRef @"InvalidHexCharacterRef"
#define kFLXmlParserErrorCodeNoDTD @"NoDTD"
#define kFLXmlParserErrorCodeAttributeNotFinished @"AttributeNotFinished"
#define kFLXmlParserErrorCodeStandaloneValue @"StandaloneValue"
#define kFLXmlParserErrorCodeInvalidEncoding @"InvalidEncoding"
#define kFLXmlParserErrorCodeStringNotStarted @"StringNotStarted"
#define kFLXmlParserErrorCodeEntityValueRequired @"EntityValueRequired"
#define kFLXmlParserErrorCodeXMLDeclNotFinished @"XMLDeclNotFinished"
#define kFLXmlParserErrorCodeInvalidConditionalSection @"InvalidConditionalSection"
#define kFLXmlParserErrorCodeEntityNotStarted @"EntityNotStarted"
#define kFLXmlParserErrorCodeEntityRefInProlog @"EntityRefInProlog"
#define kFLXmlParserErrorCodeMisplacedCDATAEndString @"MisplacedCDATAEndString"
#define kFLXmlParserErrorCodeAttributeNotStarted @"AttributeNotStarted"
#define kFLXmlParserErrorCodeUnparsedEntity @"UnparsedEntity"
#define kFLXmlParserErrorCodeCharacterRefInProlog @"CharacterRefInProlog"
#define kFLXmlParserErrorCodeExternalSubsetNotFinished @"ExternalSubsetNotFinished"
#define kFLXmlParserErrorCodeEntityBoundary @"EntityBoundary"
#define kFLXmlParserErrorCodeUnknownElement @"UnknownElement"
#define kFLXmlParserErrorCodeElementContentDeclNotFinished @"ElementContentDeclNotFinished"
#define kFLXmlParserErrorCodeEncodingNotSupported @"EncodingNotSupported"
#define kFLXmlParserErrorCodeLiteralNotFinished @"LiteralNotFinished"
#define kFLXmlParserErrorCodeObjectNotFound @"ObjectNotFound"
#define kFLXmlParserErrorCodeExtraContent @"ExtraContent"
#define kFLXmlParserErrorCodeNotationNotStarted @"NotationNotStarted"
#define kFLXmlParserErrorCodeCommentNotFinished @"CommentNotFinished"
#define kFLXmlParserErrorCodeGTRequired @"GTRequired"
#define kFLXmlParserErrorCodeEqualExpected @"EqualExpected"
#define kFLXmlParserErrorCodeParsedEntityRefInProlog @"ParsedEntityRefInProlog"
#define kFLXmlParserErrorCodeStringNotClosed @"StringNotClosed"
#define kFLXmlParserErrorCodeUndeclaredEntity @"UndeclaredEntity"
#define kFLXmlParserErrorCodeLessThanSymbolInAttribute @"LessThanSymbolInAttribute"
#define kFLXmlParserErrorCodeEmptyDocument @"EmptyDocument"
#define kFLXmlParserErrorCodeNotationNotFinished @"NotationNotFinished"
#define kFLXmlParserErrorCodeEntityReferenceMissingSemi @"EntityReferenceMissingSemi"
#define kFLXmlParserErrorCodeLiteralNotStarted @"LiteralNotStarted"
#define kFLXmlParserErrorCodeNMTOKENRequired @"NMTOKENRequired"
#define kFLXmlParserErrorCodeInvalidCharacterRef @"InvalidCharacterRef"
#define kFLXmlParserErrorCodeDelegateAbortedParse @"DelegateAbortedParse"
#define kFLXmlParserErrorCodeInternal @"Internal"
#define kFLXmlParserErrorCodeOutOfMemory @"OutOfMemory"
#define kFLXmlParserErrorCodeCharacterRefInDTD @"CharacterRefInDTD"
#define kFLXmlParserErrorCodeTagNameMismatch @"TagNameMismatch"
#define kFLXmlParserErrorCodeParsedEntityRefMissingSemi @"ParsedEntityRefMissingSemi"
#define kFLXmlParserErrorCodeNotWellBalanced @"NotWellBalanced"
#define kFLXmlParserErrorCodeMisplacedXMLDeclaration @"MisplacedXMLDeclaration"

extern NSString* FLXmlParserErrorCodeStringFromEnum(FLXmlParserErrorCode theEnum);
extern FLXmlParserErrorCode FLXmlParserErrorCodeEnumFromString(NSString* theString);

@interface FLXmlParserErrorCodeEnumSet : FLTypeSpecificEnumSet
+ (id) enumSet;
+ (id) enumSet:(NSString*) concatenatedEnumString;
@end
