// 
// FLWsdlMime.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlMime.h"
#import "FLModelObject.h"

@implementation FLWsdlMime

#if FL_MRC
- (void) dealloc {
    [_part release];
    [super dealloc];
}
#endif
@synthesize part = _part;
+ (FLWsdlMime*) wsdlMime {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
