// 
// FLWsdlPortType.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlOperation.h"
#import "FLWsdlPortType.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "FLWsdlServiceAddress.h"

@implementation FLWsdlPortType

@synthesize address = _address;
@synthesize binding = _binding;
#if FL_MRC
- (void) dealloc {
    [_binding release];
    [_operations release];
    [_name release];
    [_address release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"operation" propertyClass:[FLWsdlOperation class]] forContainerProperty:@"operations"];
}
@synthesize name = _name;
@synthesize operations = _operations;
+ (FLWsdlPortType*) wsdlPortType {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
