// 
// FLWsdlSchema.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlImport.h"
#import "FLWsdlElementBaseType.h"
#import "FLObjectDescriber.h"
#import "FLWsdlSchema.h"

@implementation FLWsdlSchema

#if FL_MRC
- (void) dealloc {
    [_imports release];
    [_elementFormDefault release];
    [_targetNamespace release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"import" propertyClass:[FLWsdlImport class]] forContainerProperty:@"imports"];
}
@synthesize elementFormDefault = _elementFormDefault;
@synthesize imports = _imports;
@synthesize targetNamespace = _targetNamespace;
+ (FLWsdlSchema*) wsdlSchema {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
