// 
// FLCodeStringBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:46 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeElement.h"

@interface FLCodeStringBaseClass : FLCodeElement {
@private
    id _string;
}

@property (readwrite, strong, nonatomic) id string;

- (id) initWithString:(id) string;
+ (id) codeString;
+ (id) codeString:(id) string;

@end
