// 
// FLCodeCompanyBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeCompanyBaseClass.h"
#import "FLModelObject.h"

@implementation FLCodeCompanyBaseClass

@synthesize address1 = _address1;
@synthesize address2 = _address2;
@synthesize address3 = _address3;
+ (id) codeCompany {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [_address2 release];
    [_phone release];
    [_website release];
    [_name release];
    [_address1 release];
    [_address3 release];
    [super dealloc];
}
#endif
@synthesize name = _name;
@synthesize phone = _phone;
@synthesize website = _website;

@end
