// 
// FLCodeCreateObjectBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:46 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeCreateObjectBaseClass.h"
#import "FLCodeElement.h"

@implementation FLCodeCreateObjectBaseClass

+ (id) codeCreateObject {
    return FLAutorelease([[[self class] alloc] init]);
}
+ (id) codeCreateObject:(id) objectType {
    return FLAutorelease([[[self class] alloc] initWithObjectType:objectType]);
}
#if FL_MRC
- (void) dealloc {
    [_objectType release];
    [super dealloc];
}
#endif
- (id) initWithObjectType:(id) objectType {
    self = [super init];
    if(self) {
        self.objectType = objectType;
    }
    return self;
}
@synthesize objectType = _objectType;

@end
