// 
// FLCodeStatementBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:44 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeElement.h"
#import "FLCodeStatementBaseClass.h"

@implementation FLCodeStatementBaseClass

+ (id) codeStatement {
    return FLAutorelease([[[self class] alloc] init]);
}
+ (id) codeStatement:(id) statement {
    return FLAutorelease([[[self class] alloc] initWithStatement:statement]);
}
#if FL_MRC
- (void) dealloc {
    [_statement release];
    [super dealloc];
}
#endif
- (id) initWithStatement:(id) statement {
    self = [super init];
    if(self) {
        self.statement = statement;
    }
    return self;
}
@synthesize statement = _statement;

@end
