// 
// FLCodeProjectBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeGeneratorOptions.h"
#import "FLCodeTypeDefinition.h"
#import "FLCodeArray.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "FLCodeEnumType.h"
#import "FLCodeObject.h"
#import "FLCodeImport.h"
#import "FLCodeDefine.h"
#import "FLCodeProjectBaseClass.h"
#import "FLCodeProjectInfo.h"

@implementation FLCodeProjectBaseClass

FLSynthesizeLazyGetterDeprecated(arrays, NSMutableArray, _arrays);
@synthesize arrays = _arrays;
FLSynthesizeLazyGetterDeprecated(classes, NSMutableArray, _classes);
@synthesize classes = _classes;
+ (id) codeProject {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize comment = _comment;
#if FL_MRC
- (void) dealloc {
    [_dependencies release];
    [_defines release];
    [_arrays release];
    [_classes release];
    [_imports release];
    [_enumTypes release];
    [_typeDefinitions release];
    [_comment release];
    [_options release];
    [_info release];
    [super dealloc];
}
#endif
FLSynthesizeLazyGetterDeprecated(defines, NSMutableArray, _defines);
@synthesize defines = _defines;
FLSynthesizeLazyGetterDeprecated(dependencies, NSMutableArray, _dependencies);
@synthesize dependencies = _dependencies;
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"dependency" propertyClass:[FLCodeTypeDefinition class]] forContainerProperty:@"dependencies"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"define" propertyClass:[FLCodeDefine class]] forContainerProperty:@"defines"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"array" propertyClass:[FLCodeArray class]] forContainerProperty:@"arrays"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"class" propertyClass:[FLCodeObject class]] forContainerProperty:@"classes"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"import" propertyClass:[FLCodeImport class]] forContainerProperty:@"imports"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"enumType" propertyClass:[FLCodeEnumType class]] forContainerProperty:@"enumTypes"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"typeDefinition" propertyClass:[FLCodeTypeDefinition class]] forContainerProperty:@"typeDefinitions"];
}
FLSynthesizeLazyGetterDeprecated(enumTypes, NSMutableArray, _enumTypes);
@synthesize enumTypes = _enumTypes;
FLSynthesizeLazyGetterDeprecated(imports, NSMutableArray, _imports);
@synthesize imports = _imports;
FLSynthesizeLazyGetterDeprecated(info, FLCodeProjectInfo, _info);
@synthesize info = _info;
FLSynthesizeLazyGetterDeprecated(options, FLCodeGeneratorOptions, _options);
@synthesize options = _options;
FLSynthesizeLazyGetterDeprecated(typeDefinitions, NSMutableArray, _typeDefinitions);
@synthesize typeDefinitions = _typeDefinitions;

@end
