// 
// FLCodeTypeBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeTypeBaseClass.h"
#import "FLModelObject.h"

@implementation FLCodeTypeBaseClass

+ (id) codeType {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [_typeName release];
    [_defaultValue release];
    [super dealloc];
}
#endif
@synthesize defaultValue = _defaultValue;
@synthesize typeName = _typeName;

@end
