// 
// FLCodeStringBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:46 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeElement.h"
#import "FLCodeStringBaseClass.h"

@implementation FLCodeStringBaseClass

+ (id) codeString {
    return FLAutorelease([[[self class] alloc] init]);
}
+ (id) codeString:(id) string {
    return FLAutorelease([[[self class] alloc] initWithString:string]);
}
#if FL_MRC
- (void) dealloc {
    [_string release];
    [super dealloc];
}
#endif
- (id) initWithString:(id) string {
    self = [super init];
    if(self) {
        self.string = string;
    }
    return self;
}
@synthesize string = _string;

@end
