// 
// FLCodeReturnBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:46 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeElement.h"
#import "FLCodeReturnBaseClass.h"

@implementation FLCodeReturnBaseClass

+ (id) codeReturn {
    return FLAutorelease([[[self class] alloc] init]);
}
+ (id) codeReturn:(id) returns {
    return FLAutorelease([[[self class] alloc] initWithReturns:returns]);
}
#if FL_MRC
- (void) dealloc {
    [_returns release];
    [super dealloc];
}
#endif
- (id) initWithReturns:(id) returns {
    self = [super init];
    if(self) {
        self.returns = returns;
    }
    return self;
}
@synthesize returns = _returns;

@end
