// 
// FLCodePropertyBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodePropertyBaseClass.h"
#import "FLCodeMethod.h"
#import "FLModelObject.h"
#import "FLCodeArrayType.h"
#import "FLObjectDescriber.h"
#import "FLCodeStorageOptions.h"

@implementation FLCodePropertyBaseClass

FLSynthesizeLazyGetterDeprecated(arrayTypes, NSMutableArray, _arrayTypes);
@synthesize arrayTypes = _arrayTypes;
@synthesize canLazyCreate = _canLazyCreate;
+ (id) codeProperty {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize comment = _comment;
#if FL_MRC
- (void) dealloc {
    [_defaultValue release];
    [_memberName release];
    [_arrayTypes release];
    [_storageOptions release];
    [_type release];
    [_comment release];
    [_setter release];
    [_getter release];
    [_storage release];
    [_name release];
    [super dealloc];
}
#endif
@synthesize defaultValue = _defaultValue;
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"arrayType" propertyClass:[FLCodeArrayType class]] forContainerProperty:@"arrayTypes"];
}
FLSynthesizeLazyGetterDeprecated(getter, FLCodeMethod, _getter);
@synthesize getter = _getter;
@synthesize isImmutable = _isImmutable;
@synthesize isPrivate = _isPrivate;
@synthesize isReadOnly = _isReadOnly;
@synthesize isStatic = _isStatic;
@synthesize isWeak = _isWeak;
@synthesize isWildcardArray = _isWildcardArray;
@synthesize memberName = _memberName;
@synthesize name = _name;
FLSynthesizeLazyGetterDeprecated(setter, FLCodeMethod, _setter);
@synthesize setter = _setter;
@synthesize storage = _storage;
- (FLCodeStorageMask) storageEnum {
    return FLCodeStorageMaskEnumFromString(self.storage);
}
- (void) setStorageEnum:(FLCodeStorageMask) value {
    self.storage = FLCodeStorageMaskStringFromEnum(value);
}
- (FLCodeStorageMaskEnumSet*) storageEnumSet {
    return [FLCodeStorageMaskEnumSet enumSet:self.storage];;
}
- (void) setStorageEnumSet:(FLCodeStorageMaskEnumSet*) value {
    self.storage = value.concatenatedString;
}
FLSynthesizeLazyGetterDeprecated(storageOptions, FLCodeStorageOptions, _storageOptions);
@synthesize storageOptions = _storageOptions;
@synthesize type = _type;
@synthesize useForEquality = _useForEquality;

@end
