// 
// FLCodeTypeBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"

@interface FLCodeTypeBaseClass : FLModelObject {
@private
    NSString* _typeName;
    NSString* _defaultValue;
}

@property (readwrite, strong, nonatomic) NSString* defaultValue;
@property (readwrite, strong, nonatomic) NSString* typeName;

+ (id) codeType;

@end
