// 
// FLCodeCommentBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeCommentBaseClass.h"
#import "FLModelObject.h"

@implementation FLCodeCommentBaseClass

+ (id) codeComment {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize comment = _comment;
@synthesize commentID = _commentID;
#if FL_MRC
- (void) dealloc {
    [_commentID release];
    [_object release];
    [_comment release];
    [super dealloc];
}
#endif
@synthesize object = _object;

@end
