// 
// FLCodePropertyNameBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:33 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "FLCodePropertyNameBaseClass.h"

@implementation FLCodePropertyNameBaseClass

+ (id) codePropertyName {
    return FLAutorelease([[[self class] alloc] init]);
}
+ (id) codePropertyName:(id) propertyName {
    return FLAutorelease([[[self class] alloc] initWithPropertyName:propertyName]);
}
#if FL_MRC
- (void) dealloc {
    [_propertyName release];
    [super dealloc];
}
#endif
- (id) initWithPropertyName:(id) propertyName {
    self = [super init];
    if(self) {
        self.propertyName = propertyName;
    }
    return self;
}
@synthesize propertyName = _propertyName;

@end
