// 
// FLCodeObjectBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"

@class FLCodeStorageOptions;
@class FLCodeTypeDefinition;
@class FLCodeMethod;
@class FLCodeConstructor;
@class FLCodeVariable;
@class FLObjectDescriber;
@class FLCodeProperty;
@class FLCodeObjectCategory;

@interface FLCodeObjectBaseClass : FLModelObject {
@private
    NSMutableArray* _methods;
    NSMutableArray* _categories;
    NSString* _protocols;
    NSMutableArray* _members;
    NSString* _superclass;
    FLCodeStorageOptions* _storageOptions;
    NSString* _comment;
    NSMutableArray* _properties;
    NSMutableArray* _dependencies;
    BOOL _isSingleton;
    NSMutableArray* _constructors;
    NSString* _name;
    BOOL _canLazyCreate;
}

@property (readwrite, assign, nonatomic) BOOL canLazyCreate;
@property (readwrite, strong, nonatomic) NSMutableArray* categories;
@property (readwrite, strong, nonatomic) NSString* comment;
@property (readwrite, strong, nonatomic) NSMutableArray* constructors;
@property (readwrite, strong, nonatomic) NSMutableArray* dependencies;
@property (readwrite, assign, nonatomic) BOOL isSingleton;
@property (readwrite, strong, nonatomic) NSMutableArray* members;
@property (readwrite, strong, nonatomic) NSMutableArray* methods;
@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, strong, nonatomic) NSMutableArray* properties;
@property (readwrite, strong, nonatomic) NSString* protocols;
@property (readwrite, strong, nonatomic) FLCodeStorageOptions* storageOptions;
@property (readwrite, strong, nonatomic) NSString* superclass;

+ (id) codeObject;

@end
