// 
// FLCodeCodeSnippetBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeCodeSnippetBaseClass.h"
#import "FLModelObject.h"

@implementation FLCodeCodeSnippetBaseClass

+ (id) codeCodeSnippet {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize comment = _comment;
#if FL_MRC
- (void) dealloc {
    [_scopedBy release];
    [_comment release];
    [_name release];
    [_lines release];
    [super dealloc];
}
#endif
@synthesize lines = _lines;
@synthesize name = _name;
@synthesize scopedBy = _scopedBy;

@end
