// 
// FLCodeGetPropertyValueBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:44 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeGetPropertyValueBaseClass.h"
#import "FLCodeElement.h"

@implementation FLCodeGetPropertyValueBaseClass

+ (id) codeGetPropertyValue {
    return FLAutorelease([[[self class] alloc] init]);
}
+ (id) codeGetPropertyValue:(id) object property:(id) property {
    return FLAutorelease([[[self class] alloc] initWithObject:object property:property]);
}
#if FL_MRC
- (void) dealloc {
    [_property release];
    [_object release];
    [super dealloc];
}
#endif
- (id) initWithObject:(id) object property:(id) property {
    self = [super init];
    if(self) {
        self.object = object;
        self.property = property;
    }
    return self;
}
@synthesize object = _object;
@synthesize property = _property;

@end
