// 
// FLWsdlOperation.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLModelObject.h"

@class FLWsdlOperation;
@class FLWsdlInputOutput;

@interface FLWsdlOperation : FLModelObject {
@private
    FLWsdlInputOutput* _output;
    FLWsdlInputOutput* _input;
    NSString* _style;
    NSString* _documentation;
    NSString* _location;
    NSString* _soapAction;
    FLWsdlOperation* _operation;
    NSString* _name;
}

@property (readwrite, strong, nonatomic) NSString* documentation;
@property (readwrite, strong, nonatomic) FLWsdlInputOutput* input;
@property (readwrite, strong, nonatomic) NSString* location;
@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, strong, nonatomic) FLWsdlOperation* operation;
@property (readwrite, strong, nonatomic) FLWsdlInputOutput* output;
@property (readwrite, strong, nonatomic) NSString* soapAction;
@property (readwrite, strong, nonatomic) NSString* style;

+ (FLWsdlOperation*) wsdlOperation;

@end
