// 
// FLWsdlMessage.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLModelObject.h"

@class FLWsdlPart;
@class FLObjectDescriber;

@interface FLWsdlMessage : FLModelObject {
@private
    NSString* _name;
    NSMutableArray* _parts;
}

@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, strong, nonatomic) NSMutableArray* parts;

+ (FLWsdlMessage*) wsdlMessage;

@end
