// 
// FLWsdlExtension.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlSequenceArray.h"
#import "FLModelObject.h"
#import "FLWsdlExtension.h"

@implementation FLWsdlExtension

@synthesize base = _base;
#if FL_MRC
- (void) dealloc {
    [_base release];
    [_sequence release];
    [super dealloc];
}
#endif
@synthesize sequence = _sequence;
+ (FLWsdlExtension*) wsdlExtension {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
