// 
// FLWsdlContent.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLModelObject.h"
#import "FLWsdlContent.h"

@implementation FLWsdlContent

#if FL_MRC
- (void) dealloc {
    [_type release];
    [super dealloc];
}
#endif
@synthesize type = _type;
+ (FLWsdlContent*) wsdlContent {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
