// 
// FLWsdlSimpleType.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLModelObject.h"

@class FLWsdlRestrictionArray;
@class FLWsdlList;

@interface FLWsdlSimpleType : FLModelObject {
@private
    NSString* _name;
    FLWsdlRestrictionArray* _restriction;
    FLWsdlList* _list;
}

@property (readwrite, strong, nonatomic) FLWsdlList* list;
@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, strong, nonatomic) FLWsdlRestrictionArray* restriction;

+ (FLWsdlSimpleType*) wsdlSimpleType;

@end
