// 
// FLWsdlBinding.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlBinding.h"
#import "FLWsdlOperation.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"

@implementation FLWsdlBinding

@synthesize binding = _binding;
#if FL_MRC
- (void) dealloc {
    [_binding release];
    [_style release];
    [_verb release];
    [_transport release];
    [_type release];
    [_name release];
    [_operations release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"operation" propertyClass:[FLWsdlOperation class]] forContainerProperty:@"operations"];
}
@synthesize name = _name;
@synthesize operations = _operations;
@synthesize style = _style;
@synthesize transport = _transport;
@synthesize type = _type;
@synthesize verb = _verb;
+ (FLWsdlBinding*) wsdlBinding {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
