// 
// FLCodeClassNameBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:46 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeElement.h"

@interface FLCodeClassNameBaseClass : FLCodeElement {
@private
    id _className;
}

@property (readwrite, strong, nonatomic) id className;

- (id) initWithClassName:(id) className;
+ (id) codeClassName;
+ (id) codeClassName:(id) className;

@end
