// 
// FLCodeObjectReferenceBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:44 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeObjectReferenceBaseClass.h"
#import "FLCodeElement.h"

@implementation FLCodeObjectReferenceBaseClass

+ (id) codeObjectReference {
    return FLAutorelease([[[self class] alloc] init]);
}
+ (id) codeObjectReference:(id) object {
    return FLAutorelease([[[self class] alloc] initWithObject:object]);
}
#if FL_MRC
- (void) dealloc {
    [_object release];
    [super dealloc];
}
#endif
- (id) initWithObject:(id) object {
    self = [super init];
    if(self) {
        self.object = object;
    }
    return self;
}
@synthesize object = _object;

@end
