// 
// FLDataType.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLDataType.h"

NSString* FLDataTypeStringFromEnum(FLDataType theEnum) {
    switch(theEnum) {
        case FLDataTypeEnum:{
            return kFLDataTypeEnum;
        }
        break;
        case FLDataTypeImmuteable:{
            return kFLDataTypeImmuteable;
        }
        break;
        case FLDataTypeValue:{
            return kFLDataTypeValue;
        }
        break;
        case FLDataTypeObject:{
            return kFLDataTypeObject;
        }
        break;
    }
    return nil;
}

FLDataType FLDataTypeEnumFromString(NSString* theString) {
    static NSDictionary* s_enumLookup = nil;
    static dispatch_once_t s_lookupPredicate = 0;
    dispatch_once(&s_lookupPredicate, ^{
        s_enumLookup = [[NSDictionary alloc] initWithObjectsAndKeys:
            [NSNumber numberWithInteger:FLDataTypeEnum], [kFLDataTypeEnum lowercaseString],
            [NSNumber numberWithInteger:FLDataTypeImmuteable], [kFLDataTypeImmuteable lowercaseString],
            [NSNumber numberWithInteger:FLDataTypeValue], [kFLDataTypeValue lowercaseString],
            [NSNumber numberWithInteger:FLDataTypeObject], [kFLDataTypeObject lowercaseString],
            nil ];
    });
    NSNumber* value = [s_enumLookup objectForKey:[theString lowercaseString]];
    return value == nil ? NSNotFound : [value integerValue];
}

@implementation FLDataTypeEnumSet
+ (id) enumSet{
    return FLAutorelease([[[self class] alloc] initWithValueLookup:(FLEnumSetEnumValueLookup*)  FLDataTypeEnumFromString stringLookup:(FLEnumSetEnumStringLookup*) FLDataTypeStringFromEnum]);
}
+ (id) enumSet:(NSString*) concatenatedEnumString {
    FLDataTypeEnumSet* outObject = FLAutorelease([[[self class] alloc] initWithValueLookup:(FLEnumSetEnumValueLookup*)  FLDataTypeEnumFromString stringLookup:(FLEnumSetEnumStringLookup*) FLDataTypeStringFromEnum]);
    [outObject setConcatenatedString:concatenatedEnumString];
    return outObject;
}
@end
