// 
// FLCodeStatement.m
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/16/13 5:22 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeStatementBaseClass.h"
#import "FLCodeStatement.h"

@implementation FLCodeStatement

+ (id) codeStatement {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif

@end
