// 
// FLCodeCommentBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"

@interface FLCodeCommentBaseClass : FLModelObject {
@private
    NSString* _commentID;
    NSString* _object;
    NSString* _comment;
}

@property (readwrite, strong, nonatomic) NSString* comment;
@property (readwrite, strong, nonatomic) NSString* commentID;
@property (readwrite, strong, nonatomic) NSString* object;

+ (id) codeComment;

@end
