// 
// FLWsdlDefinitions.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLModelObject.h"

@class FLWsdlMessage;
@class FLWsdlService;
@class FLWsdlSchema;
@class FLObjectDescriber;
@class FLWsdlPortType;
@class FLWsdlBinding;

@interface FLWsdlDefinitions : FLModelObject {
@private
    FLWsdlService* _service;
    NSMutableArray* _portTypes;
    NSMutableArray* _messages;
    NSMutableArray* _types;
    NSString* _documentation;
    NSString* _targetNamespace;
    NSMutableArray* _bindings;
}

@property (readwrite, strong, nonatomic) NSMutableArray* bindings;
@property (readwrite, strong, nonatomic) NSString* documentation;
@property (readwrite, strong, nonatomic) NSMutableArray* messages;
@property (readwrite, strong, nonatomic) NSMutableArray* portTypes;
@property (readwrite, strong, nonatomic) FLWsdlService* service;
@property (readwrite, strong, nonatomic) NSString* targetNamespace;
@property (readwrite, strong, nonatomic) NSMutableArray* types;

+ (FLWsdlDefinitions*) wsdlDefinitions;

@end
