// 
// FLSlideshowOptions.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Mobile
// Schema: SlideShowObjects
// 
// Generated by: Mike Fullerton @ 5/28/13 11:20 AM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLModelObject.h"
@interface FLSlideshowOptions : FLModelObject {
@private
    BOOL _random;
    float _speed;
    BOOL _repeat;
    NSArray* _mediaItemList;
    BOOL _playMusic;
    BOOL _autoShowCaptions;
    BOOL _autoStart;
}

@property (readwrite, assign, nonatomic) BOOL random;
@property (readwrite, assign, nonatomic) float speed;
@property (readwrite, assign, nonatomic) BOOL repeat;
@property (readwrite, strong, nonatomic) NSArray* mediaItemList;
@property (readwrite, assign, nonatomic) BOOL playMusic;
@property (readwrite, assign, nonatomic) BOOL autoShowCaptions;
@property (readwrite, assign, nonatomic) BOOL autoStart;
+(FLSlideshowOptions*) slideshowOptions;
@end
