// 
// FLTwoObjects.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/1/13 2:38 PM with PackMule (3.0.0.1)
// 
// Project: FishLamp
// Schema: FLTwoObjects
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 
#import "FishLampMinimum.h"

@interface FLTwoObjects : NSObject {
@private
    id _object1;
    id _object2;
}

@property (readwrite, strong, nonatomic) id object1;
@property (readwrite, strong, nonatomic) id object2;
+ (FLTwoObjects*) twoObjects;
@end
