// 
// FLWsdlElement.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlComplexType.h"
#import "FLWsdlElement.h"
#import "FLWsdlElementBaseType.h"

@implementation FLWsdlElement

@synthesize complexType = _complexType;
#if FL_MRC
- (void) dealloc {
    [_complexType release];
    [_ref release];
    [_maxOccurs release];
    [_minOccurs release];
    [_type release];
    [_name release];
    [super dealloc];
}
#endif
@synthesize maxOccurs = _maxOccurs;
@synthesize minOccurs = _minOccurs;
@synthesize name = _name;
@synthesize nillable = _nillable;
@synthesize ref = _ref;
@synthesize type = _type;
+ (FLWsdlElement*) wsdlElement {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
