// 
// FLWsdlSequenceArray.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLModelObject.h"

@class FLObjectDescriber;
@class FLWsdlElement;

@interface FLWsdlSequenceArray : FLModelObject {
@private
    NSString* _maxOccurs;
    NSMutableArray* _elements;
    NSString* _minOccurs;
}

@property (readwrite, strong, nonatomic) NSMutableArray* elements;
@property (readwrite, strong, nonatomic) NSString* maxOccurs;
@property (readwrite, strong, nonatomic) NSString* minOccurs;

+ (FLWsdlSequenceArray*) wsdlSequenceArray;

@end
