// 
// FLWsdlPart.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLModelObject.h"
#import "FLWsdlPart.h"

@implementation FLWsdlPart

#if FL_MRC
- (void) dealloc {
    [_name release];
    [_element release];
    [_type release];
    [super dealloc];
}
#endif
@synthesize element = _element;
@synthesize name = _name;
@synthesize type = _type;
+ (FLWsdlPart*) wsdlPart {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
