// 
// FLWsdlServiceAddress.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlServiceAddress.h"
#import "FLModelObject.h"

@implementation FLWsdlServiceAddress

#if FL_MRC
- (void) dealloc {
    [_location release];
    [super dealloc];
}
#endif
@synthesize location = _location;
+ (FLWsdlServiceAddress*) wsdlServiceAddress {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
