// 
// FLWsdlRestrictionArray.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlSequenceArray.h"
#import "FLWsdlRestrictionArray.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "FLWsdlEnumeration.h"

@implementation FLWsdlRestrictionArray

@synthesize base = _base;
#if FL_MRC
- (void) dealloc {
    [_base release];
    [_sequence release];
    [_enumerations release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"enumeration" propertyClass:[FLWsdlEnumeration class]] forContainerProperty:@"enumerations"];
}
@synthesize enumerations = _enumerations;
@synthesize sequence = _sequence;
+ (FLWsdlRestrictionArray*) wsdlRestrictionArray {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
