// 
// FLWsdlMessageBody.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLModelObject.h"
#import "FLWsdlMessageBody.h"

@implementation FLWsdlMessageBody

#if FL_MRC
- (void) dealloc {
    [_use release];
    [super dealloc];
}
#endif
@synthesize use = _use;
+ (FLWsdlMessageBody*) wsdlMessageBody {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
