// 
// FLWsdlService.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "FLWsdlService.h"
#import "FLWsdlPortType.h"

@implementation FLWsdlService

#if FL_MRC
- (void) dealloc {
    [_name release];
    [_ports release];
    [_documentation release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"port" propertyClass:[FLWsdlPortType class]] forContainerProperty:@"ports"];
}
@synthesize documentation = _documentation;
@synthesize name = _name;
@synthesize ports = _ports;
+ (FLWsdlService*) wsdlService {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
