// 
// FLWsdlElementBaseType.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlElement.h"
#import "FLWsdlElementBaseType.h"
#import "FLWsdlComplexType.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "FLWsdlSimpleType.h"

@implementation FLWsdlElementBaseType

@synthesize complexTypes = _complexTypes;
#if FL_MRC
- (void) dealloc {
    [_simpleTypes release];
    [_complexTypes release];
    [_elements release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"simpleType" propertyClass:[FLWsdlSimpleType class]] forContainerProperty:@"simpleTypes"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"complexType" propertyClass:[FLWsdlComplexType class]] forContainerProperty:@"complexTypes"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"element" propertyClass:[FLWsdlElement class]] forContainerProperty:@"elements"];
}
@synthesize elements = _elements;
@synthesize simpleTypes = _simpleTypes;
+ (FLWsdlElementBaseType*) wsdlElementBaseType {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
