// 
// FLWsdlOperation.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlOperation.h"
#import "FLWsdlInputOutput.h"
#import "FLModelObject.h"

@implementation FLWsdlOperation

#if FL_MRC
- (void) dealloc {
    [_output release];
    [_input release];
    [_style release];
    [_documentation release];
    [_location release];
    [_soapAction release];
    [_operation release];
    [_name release];
    [super dealloc];
}
#endif
@synthesize documentation = _documentation;
@synthesize input = _input;
@synthesize location = _location;
@synthesize name = _name;
@synthesize operation = _operation;
@synthesize output = _output;
@synthesize soapAction = _soapAction;
@synthesize style = _style;
+ (FLWsdlOperation*) wsdlOperation {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
