// 
// FLWsdlComplexContent.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlExtension.h"
#import "FLWsdlRestrictionArray.h"
#import "FLModelObject.h"
#import "FLWsdlComplexContent.h"

@implementation FLWsdlComplexContent

#if FL_MRC
- (void) dealloc {
    [_mixed release];
    [_extension release];
    [_restriction release];
    [super dealloc];
}
#endif
@synthesize extension = _extension;
@synthesize mixed = _mixed;
@synthesize restriction = _restriction;
+ (FLWsdlComplexContent*) wsdlComplexContent {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
