// 
// FLWsdlElement.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 

#import "FLWsdlElementBaseType.h"

@class FLWsdlComplexType;

@interface FLWsdlElement : FLWsdlElementBaseType {
@private
    FLWsdlComplexType* _complexType;
    NSString* _ref;
    NSString* _maxOccurs;
    NSString* _minOccurs;
    BOOL _nillable;
    NSString* _type;
    NSString* _name;
}

@property (readwrite, strong, nonatomic) FLWsdlComplexType* complexType;
@property (readwrite, strong, nonatomic) NSString* maxOccurs;
@property (readwrite, strong, nonatomic) NSString* minOccurs;
@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, assign, nonatomic) BOOL nillable;
@property (readwrite, strong, nonatomic) NSString* ref;
@property (readwrite, strong, nonatomic) NSString* type;

+ (FLWsdlElement*) wsdlElement;

@end
