// 
// FLWsdlImport.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLModelObject.h"
#import "FLWsdlImport.h"

@implementation FLWsdlImport

#if FL_MRC
- (void) dealloc {
    [_namespace release];
    [_import release];
    [super dealloc];
}
#endif
@synthesize import = _import;
@synthesize namespace = _namespace;
+ (FLWsdlImport*) wsdlImport {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
