// 
// FLSlideshowOptions.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// 
// Project: FishLamp Mobile
// Schema: SlideShowObjects
// 
// Generated by: Mike Fullerton @ 5/28/13 11:20 AM with PackMule (3.0.0.1)
// 
// Organization: GreenTongue Software, LLC
// 
// Copywrite (C) 2013 GreenTongue Software, LLC. All rights reserved.
// 
#import "FLSlideshowOptions.h"
#import "FLModelObject.h"
@implementation FLSlideshowOptions
@synthesize random = _random;
@synthesize speed = _speed;
@synthesize repeat = _repeat;
@synthesize mediaItemList = _mediaItemList;
@synthesize playMusic = _playMusic;
@synthesize autoShowCaptions = _autoShowCaptions;
@synthesize autoStart = _autoStart;
+(FLSlideshowOptions*) slideshowOptions {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
-(void) dealloc {
    [_mediaItemList release];
    [super dealloc];
}
#endif
@end
