// 
// FLWsdlDefinitions.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/5/13 3:45 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlPortType.h"
#import "FLWsdlService.h"
#import "FLWsdlMessage.h"
#import "FLWsdlDefinitions.h"
#import "FLModelObject.h"
#import "FLObjectDescriber.h"
#import "FLWsdlSchema.h"
#import "FLWsdlBinding.h"

@implementation FLWsdlDefinitions

@synthesize bindings = _bindings;
#if FL_MRC
- (void) dealloc {
    [_service release];
    [_portTypes release];
    [_messages release];
    [_types release];
    [_documentation release];
    [_targetNamespace release];
    [_bindings release];
    [super dealloc];
}
#endif
+ (void) didRegisterObjectDescriber:(FLObjectDescriber*) describer {
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"portType" propertyClass:[FLWsdlPortType class]] forContainerProperty:@"portTypes"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"message" propertyClass:[FLWsdlMessage class]] forContainerProperty:@"messages"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"schema" propertyClass:[FLWsdlSchema class]] forContainerProperty:@"types"];
    [describer addContainerType:[FLPropertyDescriber propertyDescriber:@"binding" propertyClass:[FLWsdlBinding class]] forContainerProperty:@"bindings"];
}
@synthesize documentation = _documentation;
@synthesize messages = _messages;
@synthesize portTypes = _portTypes;
@synthesize service = _service;
@synthesize targetNamespace = _targetNamespace;
@synthesize types = _types;
+ (FLWsdlDefinitions*) wsdlDefinitions {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
