// 
// FLCodeProjectBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"

@class FLCodeGeneratorOptions;
@class FLCodeTypeDefinition;
@class FLCodeObject;
@class FLCodeProjectInfo;
@class FLCodeImport;
@class FLCodeEnumType;
@class FLCodeDefine;
@class FLCodeArray;
@class FLObjectDescriber;

@interface FLCodeProjectBaseClass : FLModelObject {
@private
    NSMutableArray* _dependencies;
    NSMutableArray* _defines;
    NSMutableArray* _arrays;
    NSMutableArray* _classes;
    NSMutableArray* _imports;
    NSMutableArray* _enumTypes;
    NSMutableArray* _typeDefinitions;
    NSString* _comment;
    FLCodeGeneratorOptions* _options;
    FLCodeProjectInfo* _info;
}

@property (readwrite, strong, nonatomic) NSMutableArray* arrays;
@property (readwrite, strong, nonatomic) NSMutableArray* classes;
@property (readwrite, strong, nonatomic) NSString* comment;
@property (readwrite, strong, nonatomic) NSMutableArray* defines;
@property (readwrite, strong, nonatomic) NSMutableArray* dependencies;
@property (readwrite, strong, nonatomic) NSMutableArray* enumTypes;
@property (readwrite, strong, nonatomic) NSMutableArray* imports;
@property (readwrite, strong, nonatomic) FLCodeProjectInfo* info;
@property (readwrite, strong, nonatomic) FLCodeGeneratorOptions* options;
@property (readwrite, strong, nonatomic) NSMutableArray* typeDefinitions;

+ (id) codeProject;

@end
