// 
// FLCodeObject.h
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/15/13 4:24 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeObjectBaseClass.h"

@interface FLCodeObject : FLCodeObjectBaseClass {
@private
}

+ (id) codeObject;

- (void) addProperties:(NSArray*) propertyArray;

- (void) addMethods:(NSArray*) methodArray;

- (void) addProperty:(FLCodeProperty*) property;

- (void) addMethod:(FLCodeMethod*) method;

- (void) addCategory:(FLCodeObjectCategory*) category;

- (void) addDependencyType:(FLCodeTypeDefinition*) def;

- (void) addMember:(FLCodeVariable*) var ;


@end
