// 
// FLCodeCodeSnippetBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"

@interface FLCodeCodeSnippetBaseClass : FLModelObject {
@private
    NSString* _scopedBy;
    NSString* _comment;
    NSString* _name;
    NSString* _lines;
}

@property (readwrite, strong, nonatomic) NSString* comment;
@property (readwrite, strong, nonatomic) NSString* lines;
@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, strong, nonatomic) NSString* scopedBy;

+ (id) codeCodeSnippet;

@end
