// 
// FLCodeConstructorParameter.h
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/16/13 5:55 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeConstructorParameterBaseClass.h"

@interface FLCodeConstructorParameter : FLCodeConstructorParameterBaseClass {
@private
}

+ (id) codeConstructorParameter;

@end
