// 
// FLCodeStorageMask.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLTypeSpecificEnumSet.h"

typedef enum {
    FLCodeStorageMaskNone = 0,
    FLCodeStorageMaskStored = 1,
    FLCodeStorageMaskRequired = 2,
    FLCodeStorageMaskPrimaryKey = 3,
    FLCodeStorageMaskIndexed = 4,
} FLCodeStorageMask;

#define kFLCodeStorageMaskIndexed @"Indexed"
#define kFLCodeStorageMaskPrimaryKey @"PrimaryKey"
#define kFLCodeStorageMaskStored @"Stored"
#define kFLCodeStorageMaskRequired @"Required"
#define kFLCodeStorageMaskNone @"None"

extern NSString* FLCodeStorageMaskStringFromEnum(FLCodeStorageMask theEnum);
extern FLCodeStorageMask FLCodeStorageMaskEnumFromString(NSString* theString);

@interface FLCodeStorageMaskEnumSet : FLTypeSpecificEnumSet
+ (id) enumSet;
+ (id) enumSet:(NSString*) concatenatedEnumString;
@end
