// 
// FLCodeCompanyBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"

@interface FLCodeCompanyBaseClass : FLModelObject {
@private
    NSString* _address2;
    NSString* _phone;
    NSString* _website;
    NSString* _name;
    NSString* _address1;
    NSString* _address3;
}

@property (readwrite, strong, nonatomic) NSString* address1;
@property (readwrite, strong, nonatomic) NSString* address2;
@property (readwrite, strong, nonatomic) NSString* address3;
@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, strong, nonatomic) NSString* phone;
@property (readwrite, strong, nonatomic) NSString* website;

+ (id) codeCompany;

@end
