// 
// FLCodeConstructorParameterBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"

@interface FLCodeConstructorParameterBaseClass : FLModelObject {
@private
    NSString* _setProperty;
    NSString* _name;
    NSString* _type;
    BOOL _passToSuper;
}

@property (readwrite, strong, nonatomic) NSString* name;
@property (readwrite, assign, nonatomic) BOOL passToSuper;
@property (readwrite, strong, nonatomic) NSString* setProperty;
@property (readwrite, strong, nonatomic) NSString* type;

+ (id) codeConstructorParameter;

@end
