// 
// FLCodeObject.m
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/15/13 4:24 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeObjectBaseClass.h"
#import "FLCodeObject.h"
#import "FLCodeMethod.h"
#import "FLCodeProperty.h"

@implementation FLCodeObject

+ (id) codeObject {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif

- (void) addMethods:(NSArray*) methodArray {
	NSMutableArray* newMethods = [NSMutableArray array];
	for(FLCodeMethod* method in methodArray) {
		BOOL foundIt = NO;
		for(FLCodeMethod* destMethod in self.methods) {
			if([destMethod.name isEqualToString:method.name]) {
				foundIt = YES;
				break;
			}
		}
		
		if(!foundIt) {
			[newMethods addObject:method];
		}
	}
	
	[self.methods addObjectsFromArray:newMethods];
}

- (void) addProperties:(NSArray*) propertyArray {

	for(FLCodeProperty* prop in propertyArray) {
		[self addProperty:prop];
	}
}

- (void) addProperty:(FLCodeProperty*) property {
       
    for(FLCodeProperty* destProp in self.properties) {
        if([destProp.name isEqualToString:property.name]) {
            return;
        }
    }        
        
    [self.properties addObject:property];
}

- (void) addMethod:(FLCodeMethod*) method {
    [self.methods addObject:method];
}

- (void) addCategory:(FLCodeObjectCategory*) category {
    [self.categories addObject:category];
}

- (void) addDependencyType:(FLCodeTypeDefinition*) def {
    [self.dependencies addObject:def];
}

- (void) addMember:(FLCodeVariable*) var {
    [self.members addObject:var];
}

@end
