// 
// FLWsdlEnumeration.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/2/13 5:36 PM with PackMule (3.0.0.100)
// 
// Project: FishLamp CodeWriter WSDL Interpreter
// Schema: FLWsdlObjects
// 
// Copyright 2013 (c) GreenTongue Software, LLC
// 


#import "FLWsdlEnumeration.h"
#import "FLModelObject.h"

@implementation FLWsdlEnumeration

#if FL_MRC
- (void) dealloc {
    [_value release];
    [super dealloc];
}
#endif
@synthesize value = _value;
+ (FLWsdlEnumeration*) wsdlEnumeration {
    return FLAutorelease([[[self class] alloc] init]);
}

@end
