// 
// FLXmlParserErrorCode.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 7/6/13 9:48 AM with PackMule (3.0.0.32)
// 
// Project: FishLamp
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLXmlParserErrorCode.h"

NSString* FLXmlParserErrorCodeStringFromEnum(FLXmlParserErrorCode theEnum) {
    switch(theEnum) {
        case FLXmlParserErrorCodeURIRequired:{
            return kFLXmlParserErrorCodeURIRequired;
        }
        break;
        case FLXmlParserErrorCodeSeparatorRequired:{
            return kFLXmlParserErrorCodeSeparatorRequired;
        }
        break;
        case FLXmlParserErrorCodeEntityRefInEpilog:{
            return kFLXmlParserErrorCodeEntityRefInEpilog;
        }
        break;
        case FLXmlParserErrorCodeInvalidCharacterInEntity:{
            return kFLXmlParserErrorCodeInvalidCharacterInEntity;
        }
        break;
        case FLXmlParserErrorCodeCharacterRefInEpilog:{
            return kFLXmlParserErrorCodeCharacterRefInEpilog;
        }
        break;
        case FLXmlParserErrorCodeNAMERequired:{
            return kFLXmlParserErrorCodeNAMERequired;
        }
        break;
        case FLXmlParserErrorCodeSpaceRequired:{
            return kFLXmlParserErrorCodeSpaceRequired;
        }
        break;
        case FLXmlParserErrorCodeInvalidDecimalCharacterRef:{
            return kFLXmlParserErrorCodeInvalidDecimalCharacterRef;
        }
        break;
        case FLXmlParserErrorCodeInvalidEncodingName:{
            return kFLXmlParserErrorCodeInvalidEncodingName;
        }
        break;
        case FLXmlParserErrorCodePublicIdentifierRequired:{
            return kFLXmlParserErrorCodePublicIdentifierRequired;
        }
        break;
        case FLXmlParserErrorCodeProcessingInstructionNotFinished:{
            return kFLXmlParserErrorCodeProcessingInstructionNotFinished;
        }
        break;
        case FLXmlParserErrorCodeEntityNotFinished:{
            return kFLXmlParserErrorCodeEntityNotFinished;
        }
        break;
        case FLXmlParserErrorCodeDocumentStart:{
            return kFLXmlParserErrorCodeDocumentStart;
        }
        break;
        case FLXmlParserErrorCodeMixedContentDeclNotFinished:{
            return kFLXmlParserErrorCodeMixedContentDeclNotFinished;
        }
        break;
        case FLXmlParserErrorCodeInvalidCharacter:{
            return kFLXmlParserErrorCodeInvalidCharacter;
        }
        break;
        case FLXmlParserErrorCodeCharacterRefAtEOF:{
            return kFLXmlParserErrorCodeCharacterRefAtEOF;
        }
        break;
        case FLXmlParserErrorCodeEntityRefLoop:{
            return kFLXmlParserErrorCodeEntityRefLoop;
        }
        break;
        case FLXmlParserErrorCodeEntityIsExternal:{
            return kFLXmlParserErrorCodeEntityIsExternal;
        }
        break;
        case FLXmlParserErrorCodeDOCTYPEDeclNotFinished:{
            return kFLXmlParserErrorCodeDOCTYPEDeclNotFinished;
        }
        break;
        case FLXmlParserErrorCodeParsedEntityRefInEpilog:{
            return kFLXmlParserErrorCodeParsedEntityRefInEpilog;
        }
        break;
        case FLXmlParserErrorCodeAttributeListNotStarted:{
            return kFLXmlParserErrorCodeAttributeListNotStarted;
        }
        break;
        case FLXmlParserErrorCodeProcessingInstructionNotStarted:{
            return kFLXmlParserErrorCodeProcessingInstructionNotStarted;
        }
        break;
        case FLXmlParserErrorCodeAttributeListNotFinished:{
            return kFLXmlParserErrorCodeAttributeListNotFinished;
        }
        break;
        case FLXmlParserErrorCodeConditionalSectionNotFinished:{
            return kFLXmlParserErrorCodeConditionalSectionNotFinished;
        }
        break;
        case FLXmlParserErrorCodeEntityRefInDTD:{
            return kFLXmlParserErrorCodeEntityRefInDTD;
        }
        break;
        case FLXmlParserErrorCodeParsedEntityRefInInternal:{
            return kFLXmlParserErrorCodeParsedEntityRefInInternal;
        }
        break;
        case FLXmlParserErrorCodeInvalidURI:{
            return kFLXmlParserErrorCodeInvalidURI;
        }
        break;
        case FLXmlParserErrorCodePCDATARequired:{
            return kFLXmlParserErrorCodePCDATARequired;
        }
        break;
        case FLXmlParserErrorCodeURIFragment:{
            return kFLXmlParserErrorCodeURIFragment;
        }
        break;
        case FLXmlParserErrorCodeCDATANotFinished:{
            return kFLXmlParserErrorCodeCDATANotFinished;
        }
        break;
        case FLXmlParserErrorCodeElementContentDeclNotStarted:{
            return kFLXmlParserErrorCodeElementContentDeclNotStarted;
        }
        break;
        case FLXmlParserErrorCodeAttributeHasNoValue:{
            return kFLXmlParserErrorCodeAttributeHasNoValue;
        }
        break;
        case FLXmlParserErrorCodeParsedEntityRefNoName:{
            return kFLXmlParserErrorCodeParsedEntityRefNoName;
        }
        break;
        case FLXmlParserErrorCodeNamespaceDeclaration:{
            return kFLXmlParserErrorCodeNamespaceDeclaration;
        }
        break;
        case FLXmlParserErrorCodeConditionalSectionNotStarted:{
            return kFLXmlParserErrorCodeConditionalSectionNotStarted;
        }
        break;
        case FLXmlParserErrorCodeLTSlashRequired:{
            return kFLXmlParserErrorCodeLTSlashRequired;
        }
        break;
        case FLXmlParserErrorCodeExternalStandaloneEntity:{
            return kFLXmlParserErrorCodeExternalStandaloneEntity;
        }
        break;
        case FLXmlParserErrorCodeUnfinishedTag:{
            return kFLXmlParserErrorCodeUnfinishedTag;
        }
        break;
        case FLXmlParserErrorCodeParsedEntityRefAtEOF:{
            return kFLXmlParserErrorCodeParsedEntityRefAtEOF;
        }
        break;
        case FLXmlParserErrorCodeCommentContainsDoubleHyphen:{
            return kFLXmlParserErrorCodeCommentContainsDoubleHyphen;
        }
        break;
        case FLXmlParserErrorCodeEntityReferenceWithoutName:{
            return kFLXmlParserErrorCodeEntityReferenceWithoutName;
        }
        break;
        case FLXmlParserErrorCodeEntityRefAtEOF:{
            return kFLXmlParserErrorCodeEntityRefAtEOF;
        }
        break;
        case FLXmlParserErrorCodeAttributeRedefined:{
            return kFLXmlParserErrorCodeAttributeRedefined;
        }
        break;
        case FLXmlParserErrorCodeMixedContentDeclNotStarted:{
            return kFLXmlParserErrorCodeMixedContentDeclNotStarted;
        }
        break;
        case FLXmlParserErrorCodeParsedEntityRefInInternalSubset:{
            return kFLXmlParserErrorCodeParsedEntityRefInInternalSubset;
        }
        break;
        case FLXmlParserErrorCodeEntityIsParameter:{
            return kFLXmlParserErrorCodeEntityIsParameter;
        }
        break;
        case FLXmlParserErrorCodeLTRequired:{
            return kFLXmlParserErrorCodeLTRequired;
        }
        break;
        case FLXmlParserErrorCodeXMLDeclNotStarted:{
            return kFLXmlParserErrorCodeXMLDeclNotStarted;
        }
        break;
        case FLXmlParserErrorCodeUnknownEncoding:{
            return kFLXmlParserErrorCodeUnknownEncoding;
        }
        break;
        case FLXmlParserErrorCodePrematureDocumentEnd:{
            return kFLXmlParserErrorCodePrematureDocumentEnd;
        }
        break;
        case FLXmlParserErrorCodeInvalidHexCharacterRef:{
            return kFLXmlParserErrorCodeInvalidHexCharacterRef;
        }
        break;
        case FLXmlParserErrorCodeNoDTD:{
            return kFLXmlParserErrorCodeNoDTD;
        }
        break;
        case FLXmlParserErrorCodeAttributeNotFinished:{
            return kFLXmlParserErrorCodeAttributeNotFinished;
        }
        break;
        case FLXmlParserErrorCodeStandaloneValue:{
            return kFLXmlParserErrorCodeStandaloneValue;
        }
        break;
        case FLXmlParserErrorCodeInvalidEncoding:{
            return kFLXmlParserErrorCodeInvalidEncoding;
        }
        break;
        case FLXmlParserErrorCodeStringNotStarted:{
            return kFLXmlParserErrorCodeStringNotStarted;
        }
        break;
        case FLXmlParserErrorCodeEntityValueRequired:{
            return kFLXmlParserErrorCodeEntityValueRequired;
        }
        break;
        case FLXmlParserErrorCodeXMLDeclNotFinished:{
            return kFLXmlParserErrorCodeXMLDeclNotFinished;
        }
        break;
        case FLXmlParserErrorCodeInvalidConditionalSection:{
            return kFLXmlParserErrorCodeInvalidConditionalSection;
        }
        break;
        case FLXmlParserErrorCodeEntityNotStarted:{
            return kFLXmlParserErrorCodeEntityNotStarted;
        }
        break;
        case FLXmlParserErrorCodeEntityRefInProlog:{
            return kFLXmlParserErrorCodeEntityRefInProlog;
        }
        break;
        case FLXmlParserErrorCodeMisplacedCDATAEndString:{
            return kFLXmlParserErrorCodeMisplacedCDATAEndString;
        }
        break;
        case FLXmlParserErrorCodeAttributeNotStarted:{
            return kFLXmlParserErrorCodeAttributeNotStarted;
        }
        break;
        case FLXmlParserErrorCodeUnparsedEntity:{
            return kFLXmlParserErrorCodeUnparsedEntity;
        }
        break;
        case FLXmlParserErrorCodeCharacterRefInProlog:{
            return kFLXmlParserErrorCodeCharacterRefInProlog;
        }
        break;
        case FLXmlParserErrorCodeExternalSubsetNotFinished:{
            return kFLXmlParserErrorCodeExternalSubsetNotFinished;
        }
        break;
        case FLXmlParserErrorCodeEntityBoundary:{
            return kFLXmlParserErrorCodeEntityBoundary;
        }
        break;
        case FLXmlParserErrorCodeUnknownElement:{
            return kFLXmlParserErrorCodeUnknownElement;
        }
        break;
        case FLXmlParserErrorCodeElementContentDeclNotFinished:{
            return kFLXmlParserErrorCodeElementContentDeclNotFinished;
        }
        break;
        case FLXmlParserErrorCodeEncodingNotSupported:{
            return kFLXmlParserErrorCodeEncodingNotSupported;
        }
        break;
        case FLXmlParserErrorCodeLiteralNotFinished:{
            return kFLXmlParserErrorCodeLiteralNotFinished;
        }
        break;
        case FLXmlParserErrorCodeObjectNotFound:{
            return kFLXmlParserErrorCodeObjectNotFound;
        }
        break;
        case FLXmlParserErrorCodeExtraContent:{
            return kFLXmlParserErrorCodeExtraContent;
        }
        break;
        case FLXmlParserErrorCodeNotationNotStarted:{
            return kFLXmlParserErrorCodeNotationNotStarted;
        }
        break;
        case FLXmlParserErrorCodeCommentNotFinished:{
            return kFLXmlParserErrorCodeCommentNotFinished;
        }
        break;
        case FLXmlParserErrorCodeGTRequired:{
            return kFLXmlParserErrorCodeGTRequired;
        }
        break;
        case FLXmlParserErrorCodeEqualExpected:{
            return kFLXmlParserErrorCodeEqualExpected;
        }
        break;
        case FLXmlParserErrorCodeParsedEntityRefInProlog:{
            return kFLXmlParserErrorCodeParsedEntityRefInProlog;
        }
        break;
        case FLXmlParserErrorCodeStringNotClosed:{
            return kFLXmlParserErrorCodeStringNotClosed;
        }
        break;
        case FLXmlParserErrorCodeUndeclaredEntity:{
            return kFLXmlParserErrorCodeUndeclaredEntity;
        }
        break;
        case FLXmlParserErrorCodeLessThanSymbolInAttribute:{
            return kFLXmlParserErrorCodeLessThanSymbolInAttribute;
        }
        break;
        case FLXmlParserErrorCodeEmptyDocument:{
            return kFLXmlParserErrorCodeEmptyDocument;
        }
        break;
        case FLXmlParserErrorCodeNotationNotFinished:{
            return kFLXmlParserErrorCodeNotationNotFinished;
        }
        break;
        case FLXmlParserErrorCodeEntityReferenceMissingSemi:{
            return kFLXmlParserErrorCodeEntityReferenceMissingSemi;
        }
        break;
        case FLXmlParserErrorCodeLiteralNotStarted:{
            return kFLXmlParserErrorCodeLiteralNotStarted;
        }
        break;
        case FLXmlParserErrorCodeNMTOKENRequired:{
            return kFLXmlParserErrorCodeNMTOKENRequired;
        }
        break;
        case FLXmlParserErrorCodeInvalidCharacterRef:{
            return kFLXmlParserErrorCodeInvalidCharacterRef;
        }
        break;
        case FLXmlParserErrorCodeDelegateAbortedParse:{
            return kFLXmlParserErrorCodeDelegateAbortedParse;
        }
        break;
        case FLXmlParserErrorCodeInternal:{
            return kFLXmlParserErrorCodeInternal;
        }
        break;
        case FLXmlParserErrorCodeOutOfMemory:{
            return kFLXmlParserErrorCodeOutOfMemory;
        }
        break;
        case FLXmlParserErrorCodeCharacterRefInDTD:{
            return kFLXmlParserErrorCodeCharacterRefInDTD;
        }
        break;
        case FLXmlParserErrorCodeTagNameMismatch:{
            return kFLXmlParserErrorCodeTagNameMismatch;
        }
        break;
        case FLXmlParserErrorCodeParsedEntityRefMissingSemi:{
            return kFLXmlParserErrorCodeParsedEntityRefMissingSemi;
        }
        break;
        case FLXmlParserErrorCodeNotWellBalanced:{
            return kFLXmlParserErrorCodeNotWellBalanced;
        }
        break;
        case FLXmlParserErrorCodeMisplacedXMLDeclaration:{
            return kFLXmlParserErrorCodeMisplacedXMLDeclaration;
        }
        break;
    }
    return nil;
}

FLXmlParserErrorCode FLXmlParserErrorCodeEnumFromString(NSString* theString) {
    static NSDictionary* s_enumLookup = nil;
    static dispatch_once_t s_lookupPredicate = 0;
    dispatch_once(&s_lookupPredicate, ^{
        s_enumLookup = [[NSDictionary alloc] initWithObjectsAndKeys:
            [NSNumber numberWithInteger:FLXmlParserErrorCodeURIRequired], [kFLXmlParserErrorCodeURIRequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeSeparatorRequired], [kFLXmlParserErrorCodeSeparatorRequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityRefInEpilog], [kFLXmlParserErrorCodeEntityRefInEpilog lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInvalidCharacterInEntity], [kFLXmlParserErrorCodeInvalidCharacterInEntity lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeCharacterRefInEpilog], [kFLXmlParserErrorCodeCharacterRefInEpilog lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeNAMERequired], [kFLXmlParserErrorCodeNAMERequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeSpaceRequired], [kFLXmlParserErrorCodeSpaceRequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInvalidDecimalCharacterRef], [kFLXmlParserErrorCodeInvalidDecimalCharacterRef lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInvalidEncodingName], [kFLXmlParserErrorCodeInvalidEncodingName lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodePublicIdentifierRequired], [kFLXmlParserErrorCodePublicIdentifierRequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeProcessingInstructionNotFinished], [kFLXmlParserErrorCodeProcessingInstructionNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityNotFinished], [kFLXmlParserErrorCodeEntityNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeDocumentStart], [kFLXmlParserErrorCodeDocumentStart lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeMixedContentDeclNotFinished], [kFLXmlParserErrorCodeMixedContentDeclNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInvalidCharacter], [kFLXmlParserErrorCodeInvalidCharacter lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeCharacterRefAtEOF], [kFLXmlParserErrorCodeCharacterRefAtEOF lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityRefLoop], [kFLXmlParserErrorCodeEntityRefLoop lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityIsExternal], [kFLXmlParserErrorCodeEntityIsExternal lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeDOCTYPEDeclNotFinished], [kFLXmlParserErrorCodeDOCTYPEDeclNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeParsedEntityRefInEpilog], [kFLXmlParserErrorCodeParsedEntityRefInEpilog lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeAttributeListNotStarted], [kFLXmlParserErrorCodeAttributeListNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeProcessingInstructionNotStarted], [kFLXmlParserErrorCodeProcessingInstructionNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeAttributeListNotFinished], [kFLXmlParserErrorCodeAttributeListNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeConditionalSectionNotFinished], [kFLXmlParserErrorCodeConditionalSectionNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityRefInDTD], [kFLXmlParserErrorCodeEntityRefInDTD lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeParsedEntityRefInInternal], [kFLXmlParserErrorCodeParsedEntityRefInInternal lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInvalidURI], [kFLXmlParserErrorCodeInvalidURI lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodePCDATARequired], [kFLXmlParserErrorCodePCDATARequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeURIFragment], [kFLXmlParserErrorCodeURIFragment lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeCDATANotFinished], [kFLXmlParserErrorCodeCDATANotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeElementContentDeclNotStarted], [kFLXmlParserErrorCodeElementContentDeclNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeAttributeHasNoValue], [kFLXmlParserErrorCodeAttributeHasNoValue lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeParsedEntityRefNoName], [kFLXmlParserErrorCodeParsedEntityRefNoName lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeNamespaceDeclaration], [kFLXmlParserErrorCodeNamespaceDeclaration lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeConditionalSectionNotStarted], [kFLXmlParserErrorCodeConditionalSectionNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeLTSlashRequired], [kFLXmlParserErrorCodeLTSlashRequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeExternalStandaloneEntity], [kFLXmlParserErrorCodeExternalStandaloneEntity lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeUnfinishedTag], [kFLXmlParserErrorCodeUnfinishedTag lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeParsedEntityRefAtEOF], [kFLXmlParserErrorCodeParsedEntityRefAtEOF lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeCommentContainsDoubleHyphen], [kFLXmlParserErrorCodeCommentContainsDoubleHyphen lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityReferenceWithoutName], [kFLXmlParserErrorCodeEntityReferenceWithoutName lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityRefAtEOF], [kFLXmlParserErrorCodeEntityRefAtEOF lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeAttributeRedefined], [kFLXmlParserErrorCodeAttributeRedefined lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeMixedContentDeclNotStarted], [kFLXmlParserErrorCodeMixedContentDeclNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeParsedEntityRefInInternalSubset], [kFLXmlParserErrorCodeParsedEntityRefInInternalSubset lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityIsParameter], [kFLXmlParserErrorCodeEntityIsParameter lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeLTRequired], [kFLXmlParserErrorCodeLTRequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeXMLDeclNotStarted], [kFLXmlParserErrorCodeXMLDeclNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeUnknownEncoding], [kFLXmlParserErrorCodeUnknownEncoding lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodePrematureDocumentEnd], [kFLXmlParserErrorCodePrematureDocumentEnd lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInvalidHexCharacterRef], [kFLXmlParserErrorCodeInvalidHexCharacterRef lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeNoDTD], [kFLXmlParserErrorCodeNoDTD lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeAttributeNotFinished], [kFLXmlParserErrorCodeAttributeNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeStandaloneValue], [kFLXmlParserErrorCodeStandaloneValue lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInvalidEncoding], [kFLXmlParserErrorCodeInvalidEncoding lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeStringNotStarted], [kFLXmlParserErrorCodeStringNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityValueRequired], [kFLXmlParserErrorCodeEntityValueRequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeXMLDeclNotFinished], [kFLXmlParserErrorCodeXMLDeclNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInvalidConditionalSection], [kFLXmlParserErrorCodeInvalidConditionalSection lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityNotStarted], [kFLXmlParserErrorCodeEntityNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityRefInProlog], [kFLXmlParserErrorCodeEntityRefInProlog lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeMisplacedCDATAEndString], [kFLXmlParserErrorCodeMisplacedCDATAEndString lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeAttributeNotStarted], [kFLXmlParserErrorCodeAttributeNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeUnparsedEntity], [kFLXmlParserErrorCodeUnparsedEntity lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeCharacterRefInProlog], [kFLXmlParserErrorCodeCharacterRefInProlog lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeExternalSubsetNotFinished], [kFLXmlParserErrorCodeExternalSubsetNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityBoundary], [kFLXmlParserErrorCodeEntityBoundary lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeUnknownElement], [kFLXmlParserErrorCodeUnknownElement lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeElementContentDeclNotFinished], [kFLXmlParserErrorCodeElementContentDeclNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEncodingNotSupported], [kFLXmlParserErrorCodeEncodingNotSupported lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeLiteralNotFinished], [kFLXmlParserErrorCodeLiteralNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeObjectNotFound], [kFLXmlParserErrorCodeObjectNotFound lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeExtraContent], [kFLXmlParserErrorCodeExtraContent lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeNotationNotStarted], [kFLXmlParserErrorCodeNotationNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeCommentNotFinished], [kFLXmlParserErrorCodeCommentNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeGTRequired], [kFLXmlParserErrorCodeGTRequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEqualExpected], [kFLXmlParserErrorCodeEqualExpected lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeParsedEntityRefInProlog], [kFLXmlParserErrorCodeParsedEntityRefInProlog lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeStringNotClosed], [kFLXmlParserErrorCodeStringNotClosed lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeUndeclaredEntity], [kFLXmlParserErrorCodeUndeclaredEntity lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeLessThanSymbolInAttribute], [kFLXmlParserErrorCodeLessThanSymbolInAttribute lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEmptyDocument], [kFLXmlParserErrorCodeEmptyDocument lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeNotationNotFinished], [kFLXmlParserErrorCodeNotationNotFinished lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeEntityReferenceMissingSemi], [kFLXmlParserErrorCodeEntityReferenceMissingSemi lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeLiteralNotStarted], [kFLXmlParserErrorCodeLiteralNotStarted lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeNMTOKENRequired], [kFLXmlParserErrorCodeNMTOKENRequired lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInvalidCharacterRef], [kFLXmlParserErrorCodeInvalidCharacterRef lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeDelegateAbortedParse], [kFLXmlParserErrorCodeDelegateAbortedParse lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeInternal], [kFLXmlParserErrorCodeInternal lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeOutOfMemory], [kFLXmlParserErrorCodeOutOfMemory lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeCharacterRefInDTD], [kFLXmlParserErrorCodeCharacterRefInDTD lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeTagNameMismatch], [kFLXmlParserErrorCodeTagNameMismatch lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeParsedEntityRefMissingSemi], [kFLXmlParserErrorCodeParsedEntityRefMissingSemi lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeNotWellBalanced], [kFLXmlParserErrorCodeNotWellBalanced lowercaseString],
            [NSNumber numberWithInteger:FLXmlParserErrorCodeMisplacedXMLDeclaration], [kFLXmlParserErrorCodeMisplacedXMLDeclaration lowercaseString],
            nil ];
    });
    NSNumber* value = [s_enumLookup objectForKey:[theString lowercaseString]];
    return value == nil ? NSNotFound : [value integerValue];
}

@implementation FLXmlParserErrorCodeEnumSet
+ (id) enumSet{
    return FLAutorelease([[[self class] alloc] initWithValueLookup:(FLEnumSetEnumValueLookup*)  FLXmlParserErrorCodeEnumFromString stringLookup:(FLEnumSetEnumStringLookup*) FLXmlParserErrorCodeStringFromEnum]);
}
+ (id) enumSet:(NSString*) concatenatedEnumString {
    FLXmlParserErrorCodeEnumSet* outObject = FLAutorelease([[[self class] alloc] initWithValueLookup:(FLEnumSetEnumValueLookup*)  FLXmlParserErrorCodeEnumFromString stringLookup:(FLEnumSetEnumStringLookup*) FLXmlParserErrorCodeStringFromEnum]);
    [outObject setConcatenatedString:concatenatedEnumString];
    return outObject;
}
@end
