// 
// FLCodeConstructorBaseClass.h
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"

@class FLCodeElement;
@class FLObjectDescriber;
@class FLCodeConstructorParameter;

@interface FLCodeConstructorBaseClass : FLModelObject {
@private
    NSMutableArray* _lines;
    NSMutableArray* _parameters;
}

@property (readwrite, strong, nonatomic) NSMutableArray* lines;
@property (readwrite, strong, nonatomic) NSMutableArray* parameters;

+ (id) codeConstructor;

@end
