// 
// FLCodeTypeDefinition.m
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/15/13 4:24 PM with PackMule (3.0.0.29)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeTypeDefinitionBaseClass.h"
#import "FLCodeTypeDefinition.h"

@implementation FLCodeTypeDefinition

+ (id) codeTypeDefinition {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [super dealloc];
}
#endif

- (NSString*) description {
    return [NSString stringWithFormat:@"%@: type: %@, name: %@", [super description], self.dataType, self.typeName];
}

@end
