// 
// FLCodeDefineBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeDefineBaseClass.h"
#import "FLModelObject.h"

@implementation FLCodeDefineBaseClass

+ (id) codeDefine {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize comment = _comment;
#if FL_MRC
- (void) dealloc {
    [_value release];
    [_comment release];
    [_define release];
    [super dealloc];
}
#endif
@synthesize define = _define;
@synthesize isString = _isString;
@synthesize value = _value;

@end
