// 
// FLCodeObjectReference.h
// 
// Modifications are expected. File will not be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:15 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeObjectReferenceBaseClass.h"

@class FLCodeElement;

@interface FLCodeObjectReference : FLCodeObjectReferenceBaseClass {
@private
}

@end
