// 
// FLCodeTypeDefinitionBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLModelObject.h"
#import "FLCodeTypeDefinitionBaseClass.h"

@implementation FLCodeTypeDefinitionBaseClass

+ (id) codeTypeDefinition {
    return FLAutorelease([[[self class] alloc] init]);
}
@synthesize dataType = _dataType;
- (FLDataType) dataTypeEnum {
    return FLDataTypeEnumFromString(self.dataType);
}
- (void) setDataTypeEnum:(FLDataType) value {
    self.dataType = FLDataTypeStringFromEnum(value);
}
- (FLDataTypeEnumSet*) dataTypeEnumSet {
    return [FLDataTypeEnumSet enumSet:self.dataType];;
}
- (void) setDataTypeEnumSet:(FLDataTypeEnumSet*) value {
    self.dataType = value.concatenatedString;
}
#if FL_MRC
- (void) dealloc {
    [_typeName release];
    [_import release];
    [_dataType release];
    [super dealloc];
}
#endif
@synthesize import = _import;
@synthesize importIsPrivate = _importIsPrivate;
@synthesize typeName = _typeName;

@end
