// 
// FLCodeProjectInfoBaseClass.m
// 
// DO NOT MODIFY!! Modifications will be overwritten.
// Generated by: Mike Fullerton @ 6/27/13 5:17 PM with PackMule (3.0.0.31)
// 
// Project: FishLamp Code Generator
// 
// Copyright 2013 (c) GreenTongue Software LLC, Mike Fullerton
// The FishLamp Framework is released under the MIT License: http://fishlamp.com/license
// 

#import "FLCodeCompany.h"
#import "FLCodeProjectInfoBaseClass.h"
#import "FLModelObject.h"

@implementation FLCodeProjectInfoBaseClass

+ (id) codeProjectInfo {
    return FLAutorelease([[[self class] alloc] init]);
}
#if FL_MRC
- (void) dealloc {
    [_organization release];
    [_license release];
    [_projectName release];
    [_schemaName release];
    [super dealloc];
}
#endif
@synthesize license = _license;
FLSynthesizeLazyGetterDeprecated(organization, FLCodeCompany, _organization);
@synthesize organization = _organization;
@synthesize projectName = _projectName;
@synthesize schemaName = _schemaName;

@end
